language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '8'
script:
  - npm run test:prod && npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
